### PR TITLE
added api endpoints

### PR DESCRIPTION
**Pull request by Magnus-COWI**
added namingstandard, custom attributes, create storage. added f-Strings formatting.
added endpoints:
/data/v1
/bim360/docs

### CODE REVIEW

**Comment by petrbroz** [comment]
Thank you @Magnus-COWI, the code looks good! I would just ask for one thing - could you please move the /bim360/docs endpoints to a separate file and class? We're trying to use a consistent structure/mapping where individual Forge services are kept in separate Python files (for example, the [Data Management](https://forge.autodesk.com/en/docs/data/v2/developers_guide/overview/) service is in _dm.py_), and the groups of APIs are then encapsulated in separate Python classes (for example, the OSS APIs are in `OSSClient` class).

**Comment by petrbroz** [comment]
As for the `/data/v1` endpoints, I'm wondering whether those are really needed? And if they are, how should we include them in the code? I'm not sure if there's a recommended way to handle multiple versions of APIs within a single SDK. Perhaps we could just have a convention where modules without any version (e.g., _dm.py_) are automatically referring to the "current" version of the API (in this case, `/data/v2`), and if there's a module that refers to an older version, the version would have to be explicitly mentioned in the name, maybe something like _dm_v1.py_. What do you think?

**Comment by Magnus-COWI** [comment]
> Thank you @Magnus-COWI, the code looks good! I would just ask for one thing - could you please move the /bim360/docs endpoints to a separate file and class? We're trying to use a consistent structure/mapping where individual Forge services are kept in separate Python files (for example, the [Data Management](https://forge.autodesk.com/en/docs/data/v2/developers_guide/overview/) service is in dm.py), and the groups of APIs are then encapsulated in separate Python classes (for example, the OSS APIs are in OSSClient class).

Yes, it would make sense to move the code to a new file. Maybe a file called docs.py ?

> As for the /data/v1 endpoints, I'm wondering whether those are really needed? And if they are, how should we include them in the code? I'm not sure if there's a recommended way to handle multiple versions of APIs within a single SDK. Perhaps we could just have a convention where modules without any version (e.g., dm.py) are automatically referring to the "current" version of the API (in this case, /data/v2), and if there's a module that refers to an older version, the version would have to be explicitly mentioned in the name, maybe something like dm_v1.py. What do you think?

I am new to the Forge API and might have chosen some less optimal endpoints.
Are you saying that there exists a /data/v2 endpoint? If so, is it documented somewhere?
Or are there other endpoints better suited to getting items and creating new version and so on than the /data?

**Comment by Magnus-COWI** [comment]
Added some account admin endpoints to a new file called `accm.py`.
`dm.py` is renamed to `datam.py`.
Endpoints to document management is placed in `docm.py`.

**Comment by petrbroz** [comment]
Thanks @Magnus-COWI! The file structure we had in mind was something like this:

- _src_
  - _autodesk_forge_sdk_
    - _auth.py_ - corresponds to the [Forge Authentication](https://forge.autodesk.com/en/docs/oauth/v1/developers_guide/) **service**
    - _dm.py_ - corresponds to the [Forge Data Management](https://forge.autodesk.com/en/docs/data/v2/developers_guide/overview/) **service**
      - _DataManagementClient_ - class implementing endpoints from the **Data Management section** of the HTTP specification
      - _OSSClient_ - class implementing endpoints from the **OSS section** of the HTTP specification
    - _md.py_ - corresponds to the [Forge Model Derivative](https://forge.autodesk.com/en/docs/model-derivative/v2/developers_guide/overview/) **service**

I would say this is not as critical, though, so we can merge your code in, and update the folder structure later if needed.

**Pull request merged**
